#!/usr/bin/env bash
# debug.sh - Start OpenOCD GDB server and launch arm-none-eabi-gdb
# Usage: debug.sh <firmware.elf> [openocd.cfg]
# Exit 0: GDB session ended cleanly
# Exit 1: error starting openocd or gdb

set -euo pipefail

FIRMWARE="${1:-}"
CONFIG="${2:-openocd.cfg}"
OPENOCD_BIN="${OPENOCD_PATH:-openocd}"
GDB_PORT="${GDB_PORT:-3333}"

OPENOCD_PID=""

# Detect GDB binary
GDB_BIN=""
if command -v arm-none-eabi-gdb &>/dev/null; then
    GDB_BIN="arm-none-eabi-gdb"
elif command -v gdb-multiarch &>/dev/null; then
    GDB_BIN="gdb-multiarch"
fi

# ---- Validation ----

if [ -z "$FIRMWARE" ]; then
    echo "Usage: debug.sh <firmware.elf> [openocd.cfg]"
    echo ""
    echo "Arguments:"
    echo "  <firmware.elf>  Path to ELF file with debug symbols (required)"
    echo "  [openocd.cfg]   Path to openocd config (default: ./openocd.cfg)"
    echo ""
    echo "Note: Debug sessions require .elf files (not .hex or .bin) for source-level debugging."
    echo ""
    echo "Environment:"
    echo "  OPENOCD_PATH    Override openocd binary path"
    echo "  GDB_PORT        GDB server port (default: 3333)"
    exit 1
fi

EXT="${FIRMWARE##*.}"
if [ "$(echo "$EXT" | tr '[:upper:]' '[:lower:]')" != "elf" ]; then
    echo "ERROR: Debug sessions require an .elf file, got: $FIRMWARE" >&2
    echo "The .elf file contains debug symbols needed for source-level debugging." >&2
    echo "Use .elf (not .hex or .bin)." >&2
    exit 1
fi

if [ ! -f "$FIRMWARE" ]; then
    echo "ERROR: ELF file not found: $FIRMWARE" >&2
    exit 1
fi

if [ ! -f "$CONFIG" ]; then
    echo "ERROR: openocd config not found: $CONFIG" >&2
    echo "Generate one: ~/.claude/skills/stm32-stlink/scripts/generate_config.sh <family>" >&2
    exit 1
fi

if ! command -v "$OPENOCD_BIN" &>/dev/null; then
    echo "ERROR: openocd not found. Run check_tools.sh for install instructions." >&2
    exit 1
fi

if [ -z "$GDB_BIN" ]; then
    echo "ERROR: No ARM GDB found (tried arm-none-eabi-gdb and gdb-multiarch)." >&2
    echo "Run check_tools.sh for install instructions." >&2
    exit 1
fi

# ---- Check port availability ----

if command -v lsof &>/dev/null 2>&1; then
    if lsof -i ":$GDB_PORT" -sTCP:LISTEN &>/dev/null 2>&1; then
        echo "ERROR: Port $GDB_PORT is already in use." >&2
        echo "" >&2
        echo "Another openocd may be running. To fix:" >&2
        echo "  pkill openocd" >&2
        echo "  # or use a different port:" >&2
        echo "  GDB_PORT=3334 $0 $FIRMWARE $CONFIG" >&2
        exit 1
    fi
fi

# ---- Cleanup trap ----

cleanup() {
    if [ -n "$OPENOCD_PID" ] && kill -0 "$OPENOCD_PID" 2>/dev/null; then
        echo ""
        echo "Stopping OpenOCD (PID $OPENOCD_PID)..."
        kill "$OPENOCD_PID" 2>/dev/null || true
        wait "$OPENOCD_PID" 2>/dev/null || true
    fi
    [ -n "${OPENOCD_LOG:-}" ] && rm -f "$OPENOCD_LOG"
    [ -n "${GDBINIT_PATH:-}" ] && rm -f "$GDBINIT_PATH"
}
trap cleanup EXIT

# ---- Write .gdbinit for this session ----

GDBINIT_PATH="$(dirname "$FIRMWARE")/.gdbinit-stm32"

cat > "$GDBINIT_PATH" <<GDBINIT_EOF
# .gdbinit-stm32 — Auto-generated by stm32-stlink debug.sh
# $(date '+%Y-%m-%d %H:%M:%S')  |  ELF: $FIRMWARE

# Suppress safe-path prompt for this file
set auto-load safe-path /

# Connect to OpenOCD GDB server
target remote localhost:$GDB_PORT

# Reset and halt the target at the reset vector
monitor reset halt

# Set a breakpoint at main to stop at program entry
break main

# Display settings for embedded development
set print pretty on
set print array on
set pagination off
set confirm off

echo \n=== STM32 GDB Session ===\n
echo Type 'continue' (or 'c') to run to main\n
echo Type 'monitor reset halt' to reset at any time\n
echo See references/gdb-commands.md for embedded GDB tips\n\n
GDBINIT_EOF

# ---- Start OpenOCD in background ----

OPENOCD_LOG="$(mktemp /tmp/openocd_debug_XXXXXX.log)"

echo "=== STM32 Debug Session ==="
echo "ELF      : $FIRMWARE"
echo "Config   : $CONFIG"
echo "GDB      : $GDB_BIN"
echo "GDB port : $GDB_PORT"
echo ""
echo "Starting OpenOCD GDB server..."

"$OPENOCD_BIN" -f "$CONFIG" \
    -c "gdb_port $GDB_PORT" \
    -c "tcl_port 0" \
    -c "telnet_port 0" \
    > "$OPENOCD_LOG" 2>&1 &

OPENOCD_PID=$!

# Wait for openocd to bind the port (up to 15 seconds)
WAITED=0
while [ $WAITED -lt 30 ]; do
    if grep -q "Listening on port $GDB_PORT" "$OPENOCD_LOG" 2>/dev/null; then
        break
    fi
    if ! kill -0 "$OPENOCD_PID" 2>/dev/null; then
        echo ""
        echo "ERROR: OpenOCD exited unexpectedly." >&2
        echo ""
        echo "--- OpenOCD log ---" >&2
        cat "$OPENOCD_LOG" >&2
        echo "--- End log ---" >&2
        echo ""
        echo "Common causes:" >&2
        echo "  - ST-LINK not connected or board not powered" >&2
        echo "  - Wrong chip family in openocd.cfg (run detect_device.sh to identify)" >&2
        echo "  - Another process holds the ST-LINK (close CubeIDE, etc.)" >&2
        exit 1
    fi
    sleep 0.5
    WAITED=$((WAITED + 1))
done

if [ $WAITED -eq 30 ]; then
    echo "ERROR: OpenOCD did not start within 15 seconds." >&2
    echo ""
    cat "$OPENOCD_LOG" >&2
    exit 1
fi

echo "OpenOCD started (PID $OPENOCD_PID, port $GDB_PORT)"
echo ""
echo "Launching GDB..."
echo "---"
echo ""

# ---- Launch GDB ----
# --nh: skip ~/.gdbinit (use only our session-specific init)
# -x: source our generated init file
"$GDB_BIN" \
    --nh \
    -x "$GDBINIT_PATH" \
    "$FIRMWARE"

GDB_EXIT=$?
echo ""
echo "GDB session ended."
exit "$GDB_EXIT"
