#!/usr/bin/env bash
# generate_config.sh - Generate openocd.cfg for a given STM32 family
# Usage: generate_config.sh <family>
# Prints generated openocd.cfg to stdout.
# Exit 0: success; Exit 1: unknown family or no argument

set -euo pipefail

FAMILY="${1:-}"

usage() {
    echo "Usage: generate_config.sh <family>" >&2
    echo "" >&2
    echo "Supported families:" >&2
    echo "  f0   STM32F0x  (Cortex-M0,   48 MHz)" >&2
    echo "  f1   STM32F1x  (Cortex-M3,   72 MHz)  [Blue Pill family]" >&2
    echo "  f2   STM32F2x  (Cortex-M3,  120 MHz)" >&2
    echo "  f3   STM32F3x  (Cortex-M4F,  72 MHz)" >&2
    echo "  f4   STM32F4x  (Cortex-M4F, 168 MHz)  [most common]" >&2
    echo "  f7   STM32F7x  (Cortex-M7,  216 MHz)" >&2
    echo "  g0   STM32G0x  (Cortex-M0+,  64 MHz)" >&2
    echo "  g4   STM32G4x  (Cortex-M4F, 170 MHz)" >&2
    echo "  h7   STM32H7x  (Cortex-M7,  480 MHz)  [dual-core]" >&2
    echo "  l0   STM32L0   (Cortex-M0+,  32 MHz)  [ultra-low-power]" >&2
    echo "  l1   STM32L1   (Cortex-M3,   32 MHz)  [ultra-low-power]" >&2
    echo "  l4   STM32L4x  (Cortex-M4F,  80 MHz)  [ultra-low-power]" >&2
    echo "  l5   STM32L5x  (Cortex-M33, 110 MHz)  [TrustZone]" >&2
    echo "  u5   STM32U5x  (Cortex-M33, 160 MHz)" >&2
    echo "  wb   STM32WBx  (Cortex-M4+M0+, BT/BLE) [dual-core]" >&2
    echo "  wl   STM32WLx  (Cortex-M4+M0+, LoRa)   [dual-core]" >&2
    echo "" >&2
    echo "Example: generate_config.sh f4" >&2
    exit 1
}

if [ -z "$FAMILY" ]; then
    echo "ERROR: No STM32 family specified." >&2
    echo "" >&2
    usage
fi

# Normalize to lowercase
FAMILY="$(echo "$FAMILY" | tr '[:upper:]' '[:lower:]')"

# Map family to config parameters
case "$FAMILY" in
    f0) TARGET_CFG="stm32f0x.cfg"; FAMILY_FULL="STM32F0x"; CORE="Cortex-M0";        SPEED=1000; EXTRA_NOTE="" ;;
    f1) TARGET_CFG="stm32f1x.cfg"; FAMILY_FULL="STM32F1x"; CORE="Cortex-M3";        SPEED=1000; EXTRA_NOTE="" ;;
    f2) TARGET_CFG="stm32f2x.cfg"; FAMILY_FULL="STM32F2x"; CORE="Cortex-M3";        SPEED=2000; EXTRA_NOTE="" ;;
    f3) TARGET_CFG="stm32f3x.cfg"; FAMILY_FULL="STM32F3x"; CORE="Cortex-M4F";       SPEED=2000; EXTRA_NOTE="" ;;
    f4) TARGET_CFG="stm32f4x.cfg"; FAMILY_FULL="STM32F4x"; CORE="Cortex-M4F";       SPEED=4000; EXTRA_NOTE="" ;;
    f7) TARGET_CFG="stm32f7x.cfg"; FAMILY_FULL="STM32F7x"; CORE="Cortex-M7";        SPEED=4000; EXTRA_NOTE="" ;;
    g0) TARGET_CFG="stm32g0x.cfg"; FAMILY_FULL="STM32G0x"; CORE="Cortex-M0+";       SPEED=2000; EXTRA_NOTE="" ;;
    g4) TARGET_CFG="stm32g4x.cfg"; FAMILY_FULL="STM32G4x"; CORE="Cortex-M4F";       SPEED=4000; EXTRA_NOTE="" ;;
    h7) TARGET_CFG="stm32h7x.cfg"; FAMILY_FULL="STM32H7x"; CORE="Cortex-M7";        SPEED=4000
        EXTRA_NOTE="
# NOTE: STM32H7x is dual-core (Cortex-M7 + Cortex-M4).
# This config targets the M7 core (primary application core).
# For M4 core debugging, consult the OpenOCD STM32H7 documentation." ;;
    l0) TARGET_CFG="stm32l0.cfg";  FAMILY_FULL="STM32L0";  CORE="Cortex-M0+";       SPEED=500;  EXTRA_NOTE="
# NOTE: STM32L0 uses a slow 32 kHz oscillator at startup.
# Adapter speed is conservatively set to 500 kHz for reliable connection." ;;
    l1) TARGET_CFG="stm32l1.cfg";  FAMILY_FULL="STM32L1";  CORE="Cortex-M3";        SPEED=500;  EXTRA_NOTE="
# NOTE: STM32L1 ultra-low-power — adapter speed kept low for reliability." ;;
    l4) TARGET_CFG="stm32l4x.cfg"; FAMILY_FULL="STM32L4x"; CORE="Cortex-M4F";       SPEED=2000; EXTRA_NOTE="" ;;
    l5) TARGET_CFG="stm32l5x.cfg"; FAMILY_FULL="STM32L5x"; CORE="Cortex-M33";       SPEED=2000; EXTRA_NOTE="
# NOTE: STM32L5x includes TrustZone. Ensure TrustZone is disabled or debug
# authentication is configured if you have connection issues." ;;
    u5) TARGET_CFG="stm32u5x.cfg"; FAMILY_FULL="STM32U5x"; CORE="Cortex-M33";       SPEED=2000; EXTRA_NOTE="" ;;
    wb) TARGET_CFG="stm32wbx.cfg"; FAMILY_FULL="STM32WBx"; CORE="Cortex-M4 + M0+"; SPEED=2000
        EXTRA_NOTE="
# NOTE: STM32WBx is dual-core (Cortex-M4 user core + Cortex-M0+ BLE stack).
# ST-LINK HLA transport only supports the M4 core.
# The M0+ BLE stack is not accessible via standard debug." ;;
    wl) TARGET_CFG="stm32wlx.cfg"; FAMILY_FULL="STM32WLx"; CORE="Cortex-M4 + M0+"; SPEED=2000
        EXTRA_NOTE="
# NOTE: STM32WLx is dual-core (Cortex-M4 user core + Cortex-M0+ radio stack).
# ST-LINK HLA transport only supports the M4 core." ;;
    *)
        echo "ERROR: Unknown STM32 family: '$FAMILY'" >&2
        echo "" >&2
        usage
        ;;
esac

# Print the generated openocd.cfg
cat <<EOF
# openocd.cfg - Generated for $FAMILY_FULL ($CORE)
# Generated by stm32-stlink skill on $(date '+%Y-%m-%d')
#
# Flash:  openocd -f openocd.cfg -c "program firmware.elf verify reset exit"
# Debug:  openocd -f openocd.cfg
#         (then connect arm-none-eabi-gdb to localhost:3333)
$EXTRA_NOTE

# ST-LINK interface (supports V1, V2, V2-1, V3)
source [find interface/stlink.cfg]

# SWD transport (Serial Wire Debug — 2-pin interface)
# Change to "jtag" only if your board uses 4-wire JTAG and does not support SWD
transport select hla_swd

# Target chip family configuration
source [find target/$TARGET_CFG]

# Reset configuration
# "none"        — software reset only (works on most boards)
# "srst_only"   — use NRST pin (requires hardware NRST connection)
# "srst_nogate" — use NRST, keep debug active during reset
reset_config none

# SWD clock speed in kHz
# Lower this if you have signal integrity issues (long wires, noisy environment)
# Increase for faster programming if your connections are clean
adapter speed $SPEED

# GDB server port (default 3333, change if running multiple sessions)
# gdb_port 3333

# Telnet console port (useful for direct OpenOCD commands)
# telnet_port 4444
EOF

echo "" >&2
echo "Generated openocd.cfg for $FAMILY_FULL." >&2
echo "Save the above output as 'openocd.cfg' in your project directory." >&2
echo "" >&2
echo "Example usage after saving:" >&2
echo "  # Flash firmware:" >&2
echo "  openocd -f openocd.cfg -c \"program firmware.elf verify reset exit\"" >&2
echo "" >&2
echo "  # Or use the skill scripts:" >&2
echo "  ~/.claude/skills/stm32-stlink/scripts/flash.sh firmware.elf openocd.cfg" >&2

exit 0
